name: Ex-2
on: push
jobs:
  # editorconfig:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: editorconfig-checker/action-editorconfig-checker@main
  #     - run: editorconfig-checker
  markdown-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repo for markdown
        uses: actions/checkout@v4
      - name: Install Markdown cli
        run: |
          npm i -g cli-markdown
      - name: Apply to md files
        run: md **/*.md
  Build:
    # needs: [editorconfig]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh 
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Action to use
        with: # Parameters for the action
          name: code
          path: .
          include-hidden-files: true
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SECRET_TOKEN }}
  Linting:
    needs: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
